[package]
name = "Webassembly_with_Rust"
version = "0.1.0"
authors = ["Webchemist <yoonwonyoul@webchemist.net>"]
dependencies = ""
license = ""
repository = ""

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
